spring.application.name=transaction-service
server.port=8082
server.servlet.context-path=/transaction
spring.mongodb.uri=mongodb://mongo:27017/account-service
spring.data.mongodb.auto-index-creation=true
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=org.banking.commonlib.transaction
spring.kafka.admin.auto-create=true
banking.kafka.topics.deposit=${BANKING_TOPIC_DEPOSIT:account-deposit-transactions}
banking.kafka.topics.withdraw=${BANKING_TOPIC_WITHDRAW:account-withdraw-transactions}
banking.kafka.topics.transfer=${BANKING_TOPIC_TRANSFER:account-transfer-transactions}
banking.kafka.topics.fraud=${BANKING_TOPIC_FRAUD:account-fraud-transactions}
banking.fraud.amount-threshold=10000
banking.fraud.frequency-threshold=5
banking.fraud.frequency-window-minutes=1
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://authorization-server:9000/auth/oauth2/jwks
logging.level.org.springframework.security=trace
