spring.application.name=authorization-server
server.port=9000
logging.level.org.springframework.security=trace
server.servlet.context-path=/auth
spring.mongodb.uri=mongodb://mongo:27017/account-service
spring.data.mongodb.auto-index-creation=true
app.kafka.user-data-topic=user-create-account
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.admin.auto-create=true