spring.application.name=account-service
server.port=8081
server.servlet.context-path=/account
spring.mongodb.uri=mongodb://mongo:27017/account-service
spring.data.mongodb.auto-index-creation=false
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true
spring.kafka.admin.auto-create=false
banking.kafka.topics.deposit=${BANKING_TOPIC_DEPOSIT:account-deposit-transactions}
banking.kafka.topics.withdraw=${BANKING_TOPIC_WITHDRAW:account-withdraw-transactions}
banking.kafka.topics.transfer=${BANKING_TOPIC_TRANSFER:account-transfer-transactions}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://authorization-server:9000/auth/oauth2/jwks
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/auth
logging.level.org.springframework.security=trace
